services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: runbandits
      POSTGRES_PASSWORD: runbandits
      POSTGRES_DB: runbandits
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  pgdata: